version: '2'

services:

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  grafana:
    image: grafana/grafana:latest
    ports:
        - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - influxdb:influxdb

  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=pass

  monitoring:
    build: .
    links:
      - selenium:selenium
      - influxdb:influxdb
    volumes:
      - ./images:/monitoring/build/reports/tests/

volumes:
  grafana-storage: